# Generated by Django 4.2.3 on 2023-07-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='terminal_type',
            field=models.CharField(blank=True, default='cisco', max_length=200, null=True),
        ),
    ]
